### ISSUE TITLE
Use rspc?

### ISSUE THREAD

**Issue by Brendonovich** [VarunPotti/twidge#5]
Noticed that you're using a bunch of the Spacedrive stack, why not go one step further and use [rspc](https://rspc.otbeaumont.me)?
For reference, we declare all our api routes [here](https://github.com/spacedriveapp/spacedrive/blob/main/core/src/api/mod.rs), and expose them to Tauri with a [single plugin](https://github.com/spacedriveapp/spacedrive/blob/main/apps/desktop/src-tauri/src/main.rs#L26-L28).
We even have [autogenerated typescript bindings](https://github.com/spacedriveapp/spacedrive/blob/main/core/index.ts)!
This probably could have been a discussion but oh well we're here now.

**Comment by VarunPotti** [comment]
Wow! RSPC looks insane, will have a closer look at it sometime today. I am already spending a lot of time trying to create types and manage states and I wanted a solution like this. Cheers to you and oscar for creating such an insane tool!

**Comment by VarunPotti** [comment]
Done! I moved to rspc (#8)

**Comment by oscartbeaumont** [comment]
This is awesome to see. If you run into any problems or have any feedback feel free to reach out to me.

**Comment by VarunPotti** [comment]
> This is awesome to see. If you run into any problems or have any feedback feel free to reach out to me.

Will do! I am loving the simplicity of rspc so far. Especially the automatic type-defs.
